#cloud-config

apt_update: true

packages:
 - jmeter
 - xterm
 - xauth
 - curl

runcmd:
 - ip=$(curl http://169.254.169.254/2009-04-04/meta-data/local-ipv4)
 - sed -i -re "s/.*$(hostname).*/$ip $(hostname)/" /etc/hosts
 - sed -i -re 's/^remote_hosts=.*/remote_hosts=/' /usr/share/jmeter/bin/jmeter.properties
